### ISSUE TITLE
Another tutorial like this with Svelte?

### ISSUE THREAD

**Issue by JPT62089** [marcusolsson/obsidian-spooky#1]
Howdy!

First of all, thank you for this resource! It taught me a ton and helped me get off the ground with learning Obsidian plugins.

I'm trying to find some good resources for using Svelte in Obsidian plugins. Would you know if any good ones? I've already watched the one on the Obsidian YT channel, which was great, but it did not go into the depth that this one did.

Do you know of any good resources or plans to do another tutorial like this one but with Svelte? I'm looking specifically at the settings side of things and how to convert what this plugin did to Svelte.

**Comment by marcusolsson** [comment]
I wrote a guide on how to set up Svelte for you plugin here: 

https://marcus.se.net/obsidian-plugin-docs/getting-started/svelte

I'm also building a Svelte component library for Obsidian. It's still in early alpha so I'd recommend that you copy-paste components rather than importing the package (unless you're ok with dealing with API breakage 😅 ).

https://github.com/marcusolsson/obsidian-svelte

**Comment by JPT62089** [comment]
Hey @marcusolsson 

That last bit I missed on the first link! That helped me tremendously! Thank you! I was missing the store aspect of it and ended up finding out that I also needed to bind the input value of spookyText when defining the input.

`<input
		bind:value={plugin.settings.spookyText}
		type="text"
		on:change={plugin.saveSettings}
	/>`
